# APP PAGE
GET http://localhost:3001/

###
# INFO PAGE
GET http://localhost:3001/info

###
# GET ALL
GET http://localhost:3001/api/persons

###
# GET FIRST
GET http://localhost:3001/api/persons/5ff79cdb2737c70021b95ec6

###
# GET NOTHING BAD ID
GET http://localhost:3001/api/persons/0

###
# GET NOTHING AT GOOD ID
GET http://localhost:3001/api/persons/5ff75702d4467d1414f7516a

###
# GET NON-EXISTENT ROUTE
GET http://localhost:3001/RANDOM

###
# CREATE PERSON MISSING NAME
POST http://localhost:3001/api/persons HTTP/1.1
Content-Type: application/json

{
    "number": "12345678"
}

###
# CREATE PERSON MISSING NUMBER
POST http://localhost:3001/api/persons HTTP/1.1
Content-Type: application/json

{
    "name": "test"
}

###
# CREATE PERSON INVALID NAME
POST http://localhost:3001/api/persons HTTP/1.1
Content-Type: application/json

{
    "name": "t",
    "number": "12345678"
}

###
# CREATE PERSON INVALID NAME AND MISSING NUMBER
POST http://localhost:3001/api/persons HTTP/1.1
Content-Type: application/json

{
    "name": "t"
}

###
# CREATE PERSON INVALID NUMBER
POST http://localhost:3001/api/persons HTTP/1.1
Content-Type: application/json

{
    "name": "test",
    "number": "1"
}

###
# CREATE PERSON INVALID NAME AND NUMBER
POST http://localhost:3001/api/persons HTTP/1.1
Content-Type: application/json

{
    "name": "t",
    "number": "1"
}

###
# CREATE VALID PERSON
POST http://localhost:3001/api/persons HTTP/1.1
Content-Type: application/json

{
    "name": "TESTEST",
    "number": "12345678"
}

###
# UPDATE PERSON MISSING NUMBER
PUT http://localhost:3001/api/persons/5ff7d2df81f9384b032283e8
Content-Type: application/json

{
    "name": "TESTEST"
}

###
# UPDATE PERSON INVALID NUMBER
PUT http://localhost:3001/api/persons/5ff7d2df81f9384b032283e8
Content-Type: application/json

{
    "name": "TESTEST",
    "number": "z"
}

###
# UPDATE PERSON VALID NUMBER 
PUT http://localhost:3001/api/persons/5ff7d2df81f9384b032283e8
Content-Type: application/json

{
    "name": "TESTEST",
    "number": "87654321"
}

###
# CREATE DUPLICATE
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "TESTEST",
    "number": "87654321"
}

###
# GET ALL
GET http://localhost:3001/api/persons

###
# DELETE TEST ID
DELETE http://localhost:3001/api/persons/5ff7d2df81f9384b032283e8

###
# DELETE NOTHING BAD ID
DELETE http://localhost:3001/api/persons/0

###
# DELETE NOTHING GOOD ID
DELETE http://localhost:3001/api/persons/5ff75702d4467d1414f7516a

###
# DELETE BAD ENDPOINT
DELETE http://localhost:3001/api/persons/
